name: Cloud-Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        provider:
          - qemu/default
          - azure/default
        profile:
          - 6.8/minimal
          - 6.8/default
          - 6.8/full

    steps:
      - name: Safe provider string
        id: provider
        uses: frabert/replace-string-action@v1.2
        with:
          pattern: '(.+)\/(.+)'
          string: ${{ matrix.provider }}
          replace-with: '${1}_${2}'

      - name: Safe profile string
        id: profile
        uses: frabert/replace-string-action@v1.2
        with:
          pattern: '(.+)\/(.+)'
          string: ${{ matrix.profile }}
          replace-with: '${1}_${2}'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache mirror
        uses: actions/cache@v2
        with:
          path: mirror
          key: mirror-${{ steps.profile.outputs.result }}

      - name: Install host tools
        run: sudo scripts/host-setup.sh

      - name: Make image
        run: make PROFILE=${{ matrix.profile }} PROVIDER=${{ matrix.provider }}
        timeout-minutes: 30
